# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

exclude: |
  ^wandb/
  ^data/
  ^reports/
  ^.venv/
  ^.pytest_cache/

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.7
    hooks:
      # Lint and autofix
      - id: ruff
        args: ["--fix"]

      # Formatter (replaces black)
      - id: ruff-format

      # Strict check (CI safety net)
      - id: ruff
